name: hny
description: A Hacker News Browser

version: 0.1.0+1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_core: ^0.2.5
  firebase_database: ^1.0.4
  json_annotation: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^1.0.0
  build_runner: ^0.10.0

flutter:
  uses-material-design: true
